---
ms.openlocfilehash: 75fcd5b00ea5cac218a9f7809c53b179df97825c
ms.sourcegitcommit: 3fc033b6e98ed7ecdf46a85c79b00a3a3ddcf963
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/18/2019
ms.locfileid: "47229976"
---
# <a name="exceptions"></a><span data-ttu-id="9de28-101">Özel Durumlar</span><span class="sxs-lookup"><span data-stu-id="9de28-101">Exceptions</span></span>

<span data-ttu-id="9de28-102">C# dilinde özel durumlar hem sistem düzeyinde hem de uygulama düzeyinde işleme yapılandırılmış, Tekdüzen ve tür kullanımı uyumlu bir yol sağlar hata koşulları.</span><span class="sxs-lookup"><span data-stu-id="9de28-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="9de28-103">C# dilinde özel durum mekanizması ile bazı önemli farklar oldukça, C++, benzer:</span><span class="sxs-lookup"><span data-stu-id="9de28-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="9de28-104">C# ' ta tüm özel durumlar, türetilen bir sınıf türünün bir örneği tarafından temsil edilmesi gereken `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="9de28-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="9de28-105">C++'da, herhangi bir değer herhangi bir türde bir özel durum temsil etmek için kullanılabilir.</span><span class="sxs-lookup"><span data-stu-id="9de28-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="9de28-106">C# ' ta, bir finally bloğunda ([try deyimi](statements.md#the-try-statement)) hem normal yürütmenin hem de özel durumları yürüten sonlandırma kodu yazmak için kullanılır.</span><span class="sxs-lookup"><span data-stu-id="9de28-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="9de28-107">Bu tür kod kod yinelemeden C++ olarak yazabilir zordur.</span><span class="sxs-lookup"><span data-stu-id="9de28-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="9de28-108">C# ' ta, sistem düzeyinde özel durumlar gibi taşma sıfırla bölme ve null başvuru özel durum sınıfları iyi tanımlanmış ve uygulama düzeyi hata koşulları ile ilgili bir değer alır.</span><span class="sxs-lookup"><span data-stu-id="9de28-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="9de28-109">Özel durumların nedenlerini</span><span class="sxs-lookup"><span data-stu-id="9de28-109">Causes of exceptions</span></span>

<span data-ttu-id="9de28-110">İki farklı şekilde, özel durum.</span><span class="sxs-lookup"><span data-stu-id="9de28-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="9de28-111">A `throw` deyimi ([fırlatma](statements.md#the-throw-statement)) koşulsuz olarak ve hemen bir özel durum oluşturur.</span><span class="sxs-lookup"><span data-stu-id="9de28-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="9de28-112">Denetim, hiçbir zaman hemen sonrasındaki deyime ulaştığında `throw`.</span><span class="sxs-lookup"><span data-stu-id="9de28-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="9de28-113">İşlem normal şekilde tamamlanamıyor ifadesi C# ifadeleri ve işleme sırasında ortaya belirli özel durumları bazı durumlarda bir özel durum neden.</span><span class="sxs-lookup"><span data-stu-id="9de28-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="9de28-114">Örneğin, bir tamsayı bölme işlemi ([bölme işleci](expressions.md#division-operator)) oluşturur bir `System.DivideByZeroException` payda sıfır ise.</span><span class="sxs-lookup"><span data-stu-id="9de28-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="9de28-115">Bkz: [genel özel durum sınıfları](exceptions.md#common-exception-classes) bu şekilde oluşabilecek çeşitli özel durumların bir listesi için.</span><span class="sxs-lookup"><span data-stu-id="9de28-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="9de28-116">System.Exception sınıfı</span><span class="sxs-lookup"><span data-stu-id="9de28-116">The System.Exception class</span></span>

<span data-ttu-id="9de28-117">`System.Exception` Sınıfı, tüm özel durumlar'ın temel türü.</span><span class="sxs-lookup"><span data-stu-id="9de28-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="9de28-118">Bu sınıf, tüm özel durumları paylaşan birkaç önemli özelliklere sahiptir:</span><span class="sxs-lookup"><span data-stu-id="9de28-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="9de28-119">`Message` salt okunur bir özellik türü `string` , insanlar tarafından okunabilen bir özel durumun nedenini açıklamasını içerir.</span><span class="sxs-lookup"><span data-stu-id="9de28-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="9de28-120">`InnerException` salt okunur bir özellik türü `Exception`.</span><span class="sxs-lookup"><span data-stu-id="9de28-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="9de28-121">Değeri null olmayan ise, geçerli özel duruma neden olan özel durum başvurduğu — diğer bir deyişle, geçerli özel durum bir catch bloğu içinde tetiklendi işleme `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="9de28-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="9de28-122">Aksi takdirde, değeri bu özel durumun başka bir özel durumun nedeni olduğunu gösteren null olur.</span><span class="sxs-lookup"><span data-stu-id="9de28-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="9de28-123">Bu şekilde birbirine zincirlenmiş özel durum nesne sayısını rastgele olabilir.</span><span class="sxs-lookup"><span data-stu-id="9de28-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="9de28-124">Bu özelliklerin değerini örnek oluşturucusu için yapılan çağrıda belirtilen `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="9de28-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="9de28-125">Özel durumları nasıl işlenir?</span><span class="sxs-lookup"><span data-stu-id="9de28-125">How exceptions are handled</span></span>

<span data-ttu-id="9de28-126">Özel durumlar tarafından işlendiğinden bir `try` deyimi ([try deyimi](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="9de28-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="9de28-127">Bir özel durum oluştuğunda sistem arar en yakın `catch` çalışma zamanı özel durum türüne göre belirlenen özel durumu işleyebilen yan tümcesi.</span><span class="sxs-lookup"><span data-stu-id="9de28-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="9de28-128">İlk olarak, geçerli yöntemi bir sözcüksel olarak kapsayan için aranır `try` deyimi ve ilişkili bir catch yan tümceleri, try deyimi sırayla değerlendirilir.</span><span class="sxs-lookup"><span data-stu-id="9de28-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="9de28-129">Bu başarısız olursa geçerli yöntemi çağıran yönteme bir sözcüksel olarak kapsayan için aranır `try` geçerli yöntemine çağrı noktasındaki kapsayan deyimi.</span><span class="sxs-lookup"><span data-stu-id="9de28-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="9de28-130">Bu arama kadar devam bir `catch` yan tümcesi işleyebilen geçerli özel durum, aynı sınıfa veya temel bir sınıfı, çalışma zamanı türü olan özel durum bir özel durum sınıfı adlandırarak bulundu.</span><span class="sxs-lookup"><span data-stu-id="9de28-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="9de28-131">A `catch` bir özel durum sınıfı adı değil yan tümcesi tüm özel işleyebilir.</span><span class="sxs-lookup"><span data-stu-id="9de28-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="9de28-132">Eşleşen bir catch yan tümcesi bulunduktan sonra sistem denetimi catch yan tümcesinin ilk deyime aktarmak hazırlar.</span><span class="sxs-lookup"><span data-stu-id="9de28-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="9de28-133">Catch yan tümcesinin yürütme başlamadan önce sistem, sırasıyla herhangi yürütür `finally` daha fazla deneyin deyimleri ile ilişkili yan tümceleri iç içe geçmiş, özel durum yakalandı hesaptan.</span><span class="sxs-lookup"><span data-stu-id="9de28-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="9de28-134">Eşleşen bir catch yan tümcesi bulunursa ikisinden biri gerçekleşir:</span><span class="sxs-lookup"><span data-stu-id="9de28-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="9de28-135">Eşleşen bir catch yan tümcesi arama statik Oluşturucu ulaşırsa ([statik oluşturucular](classes.md#static-constructors)) veya statik alan başlatıcısında bir `System.TypeInitializationException` statik oluşturucunun çağrılacağını tetikleyen noktada oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="9de28-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="9de28-136">İç özel duruma `System.TypeInitializationException` orijinal olarak oluşturulan özel durum içerir.</span><span class="sxs-lookup"><span data-stu-id="9de28-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="9de28-137">Catch yan tümceleri eşleştirme için arama ilk iş parçacığı çalışmaya kod ulaşırsa, iş parçacığının yürütülmesini sona erdirilir.</span><span class="sxs-lookup"><span data-stu-id="9de28-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="9de28-138">Bu tür sonlandırma uygulama tanımlı etkisidir.</span><span class="sxs-lookup"><span data-stu-id="9de28-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="9de28-139">Yıkıcı yürütme sırasında gerçekleşen özel olarak belirtilmelidir özel durumlardır.</span><span class="sxs-lookup"><span data-stu-id="9de28-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="9de28-140">Yıkıcı yürütülürken bir özel durum oluşur ve bu özel durum yakalanmadı, bu yok edici yürütülmesi sonlandırıldı ve (varsa) temel sınıfın yok Edicisi çağrılır.</span><span class="sxs-lookup"><span data-stu-id="9de28-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="9de28-141">Hiçbir temel sınıf varsa (olarak durumunda `object` türü) veya hiçbir taban sınıf yok edicisini yoktur. ardından özel durumu atılır.</span><span class="sxs-lookup"><span data-stu-id="9de28-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="9de28-142">Sık karşılaşılan özel durum sınıfları</span><span class="sxs-lookup"><span data-stu-id="9de28-142">Common Exception Classes</span></span>

<span data-ttu-id="9de28-143">Aşağıdaki özel durumlar, belirli C# işlemleri tarafından atılır.</span><span class="sxs-lookup"><span data-stu-id="9de28-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="9de28-144">Gibi aritmetik işlemler sırasında oluşan özel durumlar için temel sınıf `System.DivideByZeroException` ve `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="9de28-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="9de28-145">Gerçek depolanan öğenin türünü dizinin gerçek türü ile uyumsuz olduğundan bir depolama dizisine başarısız olduğunda oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="9de28-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="9de28-146">Bir tamsayı değeri sıfıra bölünme girişimi oluştuğunda oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="9de28-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="9de28-147">Sıfırdan küçük veya dizi sınırları dışında bir dizin aracılığıyla bir dizi dizini girişimi zaman oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="9de28-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="9de28-148">Çalışma zamanında bir taban türü veya arabirim için türetilmiş bir tür açık bir dönüştürme başarısız olduğunda oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="9de28-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="9de28-149">Oluşan bir `null` başvurusu gerekli olarak başvurulan nesnenin neden olan bir şekilde kullanılır.</span><span class="sxs-lookup"><span data-stu-id="9de28-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="9de28-150">Bellek ayırma girişimi zaman oluşturulur (aracılığıyla `new`) başarısız olur.</span><span class="sxs-lookup"><span data-stu-id="9de28-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="9de28-151">Aritmetik işlemin içinde olduğunda oluşturulan bir `checked` bağlam taşıyor.</span><span class="sxs-lookup"><span data-stu-id="9de28-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="9de28-152">Çok fazla bekleyen yöntem çağrılarını sağlayarak yürütme yığın kaldığında oluşturulur; genellikle vurgulayan çok derin ya da sınırlandırılmamış özyineleme.</span><span class="sxs-lookup"><span data-stu-id="9de28-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="9de28-153">Statik oluşturucu yok ve özel durum oluşturduğunda durum `catch` yan tümceleri var. Bunu yakalayıp yakalamayacağınıza karar.</span><span class="sxs-lookup"><span data-stu-id="9de28-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
